package controller.database;

import java.sql.Connection;
import java.sql.Statement;

public class CreateTable {
    public static void createTable(Connection connection) {

        try (Statement stmt = connection.createStatement()) {
            String sql = "CREATE TABLE IF NOT EXISTS CAR" +
                    "(ID INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                    " NAME           CHAR(50)    NOT NULL, " +
                    " DATE           DATE        NOT NULL, " +
                    " COLOR          CHAR(50)    NOT NULL, " +
                    " ISAFTERCRASH   BOOLEAN)";
            stmt.executeUpdate(sql);

        } catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }
        System.out.println("Table created successfully");
    }
}
